FROM golang:1.23 AS builder

WORKDIR /app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/frontend-app ./frontend/cmd/app

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/frontend-app /app/frontend-app
COPY --from=builder /app/frontend/templates /app/templates
COPY --from=builder /app/frontend/static /app/static

ENV FRONTEND_PORT=8080

EXPOSE 8080

ENTRYPOINT ["/app/frontend-app"] 